export const TODOS = [{
    id: 1,
    title: "Go to Gym",
    description: "Hit the gym from 7-9"
}, {
    id: 2,
    title: "Go to eat food",
    description: "Eat food from from 9-11"
},]

// const fetchedTodos=async function(){
//     let res=await fetch("https://sum-server.100xdevs.com/todos");
//     res=await res.json();
//     return res.todos;
// }

// export const TODOS=await fetchedTodos();